import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider, useMessages } from 'next-intl';
import JotaiProvider from "@/components/JotaiProvider";
import Navigation from "@/components/Navigation";
import ScrollToTopButton from "@/components/ScrollToTopButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HSR FreeSR Relic code generate",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body className={inter.className + " container mx-auto relative"}>
        <NextIntlClientProvider messages={messages}>
          <JotaiProvider>
            <Navigation />
            <div className="fixed bottom-1 right-1 z-50">
              <ScrollToTopButton />
            </div>
            <div className="fixed bottom-1 left-6 z-50 text-[6pt] text-gray-600">
              {`20240301.2231`}
            </div>
            {children}
          </JotaiProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
