import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider, useMessages } from 'next-intl';
import LocaleSwitcher from "@/components/LocaleSwitcher";
import JotaiProvider from "@/components/JotaiProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HSR FreeSR Relic code generate",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body className={inter.className + " container mx-auto relative pb-9"}>
        <NextIntlClientProvider messages={messages}>
          <JotaiProvider>
            <div className="fixed top-1 left-1 z-50 text-[6pt] text-gray-600 flex flex-col">
              <LocaleSwitcher />
              {`20240227.0021`}
            </div>
            {children}
          </JotaiProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
